# Site
repository: xzile/xzile.github.io
favicon: assets/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jonathan Hopson
title: Sr. Software Engineer
#email: xzile.jonhopson@gmail.com
# email_title: Email (Email title override)
#phone: 606-687-0745
# phone_title: Phone (Phone title override)
website: https://github.com/xzile
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: jon_hopson
github_username:  xzile
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: jonathan-hopson-37831158
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/headshot.jpg
about_content: | # this will include new lines to allow paragraphs
  Self-motivated problem solver. I have worked in the higher education software business since 2007; working remotely from my home in Tennessee on teams ranging from 2 to 15.

  Strengths:
  - PHP / Laravel
  - Ruby / Rails
  - Database Design, Performance, and Optimization
  - AWS Services

  Emerging Interests:
  - Front-end Engineering (Angular)
  - Erlang / Elixir

content:
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Interfolio
        sub_title: Sr. Software Engineer
        caption: January 2017 - present
        link: https://interfolio.com
#        quote: >
#          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Interfolio acquired Data180 in January 2017. Initially, I assisted in the transition of Faculty180 into the Interfolio ecosystem. This included a migration to Git, moving hosting to AWS, integrating Laravel into our legacy monolith, and adapting users and authentication to the existing Interfolio infrastructure.

          Over time, I expanded to develop and maintain a majority of the Interfolio backend software suite, largely written in Ruby/Rails.  While also helping design and develop several greenfield microservices, as well as automation integration software for the CI/CD process.

          Skills include:
          - PHP/Laravel
          - Ruby/Rails
          - GraphQL
          - PostgreSQL
          - MySQL
          - Git
          - Docker
          - AWS Services (S3, SNS, SQS, DynamoDB, etc.)
          - Integration with internal and third-party software
          - Agile Software Development
      - layout: right
        title: Data180
        sub_title: Software Engineer
        caption: March 2007 - January 2017
        link: https://data180.com
#        quote: >
#          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          From a brief stint as QA as I finished my degree. I was later hired on as a full-time software engineer to help develop and support Data180’s flagship product, Faculty180, a higher-education faculty data and activity tracking system.

          Later on, I was the lead engineer for their student product, which supported students and schools with activity tracking, co-curricular transcripts, resumes, and assessments.

          Skills include:
          - PHP
          - PostgreSQL
          - jQuery
          - SVN
          - Integration with third party APIs
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Morehead State University
        sub_title: Bachelors in Business Administration (Computer Information Systems)
        caption: 2003 - 2007
#        quote: >
#          Short institution or course description (optional)
#        description: | # this will include new lines to allow paragraphs
#          Description of qualification
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I love writing software and building solutions. When I’m not problem-solving via code, I’m problem-solving or puzzle creating in Dungeons & Dragons as both a player and a game master.

      D&D teaches many non-technical skills. As a player, you are constantly working as a team, playing off your party members' strengths and understanding each other's weaknesses. It also teaches you how to share the spotlight amongst a group, taking strides to both lead and follow.

      As a game master, your responsibilities are endless. Quick decision making, designing encounters to both challenges and showcase your players, and describe the world your players are in and the individuals they are interacting with. Thinking on your feet is a necessity, as a group of unpredictable players can quickly throw a wrench into any pre-planned ideas you have.

# Footer
#footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
